/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SecteursRouteImport } from './routes/secteurs'
import { Route as ProjetsRouteImport } from './routes/projets'
import { Route as PourquoiRouteImport } from './routes/pourquoi'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as ActivitesRouteImport } from './routes/activites'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SecteursRoute = SecteursRouteImport.update({
  id: '/secteurs',
  path: '/secteurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetsRoute = ProjetsRouteImport.update({
  id: '/projets',
  path: '/projets',
  getParentRoute: () => rootRouteImport,
} as any)
const PourquoiRoute = PourquoiRouteImport.update({
  id: '/pourquoi',
  path: '/pourquoi',
  getParentRoute: () => rootRouteImport,
} as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitesRoute = ActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activites': typeof ActivitesRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/partenaires': typeof PartenairesRoute
  '/pourquoi': typeof PourquoiRoute
  '/projets': typeof ProjetsRoute
  '/secteurs': typeof SecteursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activites': typeof ActivitesRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/partenaires': typeof PartenairesRoute
  '/pourquoi': typeof PourquoiRoute
  '/projets': typeof ProjetsRoute
  '/secteurs': typeof SecteursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/activites': typeof ActivitesRoute
  '/catalogue': typeof CatalogueRoute
  '/contact': typeof ContactRoute
  '/partenaires': typeof PartenairesRoute
  '/pourquoi': typeof PourquoiRoute
  '/projets': typeof ProjetsRoute
  '/secteurs': typeof SecteursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/activites'
    | '/catalogue'
    | '/contact'
    | '/partenaires'
    | '/pourquoi'
    | '/projets'
    | '/secteurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/activites'
    | '/catalogue'
    | '/contact'
    | '/partenaires'
    | '/pourquoi'
    | '/projets'
    | '/secteurs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/activites'
    | '/catalogue'
    | '/contact'
    | '/partenaires'
    | '/pourquoi'
    | '/projets'
    | '/secteurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ActivitesRoute: typeof ActivitesRoute
  CatalogueRoute: typeof CatalogueRoute
  ContactRoute: typeof ContactRoute
  PartenairesRoute: typeof PartenairesRoute
  PourquoiRoute: typeof PourquoiRoute
  ProjetsRoute: typeof ProjetsRoute
  SecteursRoute: typeof SecteursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/secteurs': {
      id: '/secteurs'
      path: '/secteurs'
      fullPath: '/secteurs'
      preLoaderRoute: typeof SecteursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projets': {
      id: '/projets'
      path: '/projets'
      fullPath: '/projets'
      preLoaderRoute: typeof ProjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pourquoi': {
      id: '/pourquoi'
      path: '/pourquoi'
      fullPath: '/pourquoi'
      preLoaderRoute: typeof PourquoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activites': {
      id: '/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof ActivitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ActivitesRoute: ActivitesRoute,
  CatalogueRoute: CatalogueRoute,
  ContactRoute: ContactRoute,
  PartenairesRoute: PartenairesRoute,
  PourquoiRoute: PourquoiRoute,
  ProjetsRoute: ProjetsRoute,
  SecteursRoute: SecteursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
